name: IndexNow

on:
  push:
    branches:
      - main

jobs:
  indexnow:
    runs-on: ubuntu-latest

    steps:
      - name: Get URLs from sitemap
        run: |
          curl https://sellvpn.net/sitemap.xml | grep -oP '(?<=<loc>)[^<]+' > urls.txt

      - name: Submit to IndexNow
        run: |
          urls=$(jq -R . < urls.txt | jq -s .)
          curl -X POST "https://api.indexnow.org/indexnow" \
          -H "Content-Type: application/json" \
          -d "{
            \"host\": \"sellvpn.net\",
            \"key\": \"47592892f8844e74976c2ed3dc62b730\",
            \"keyLocation\": \"https://sellvpn.net/47592892f8844e74976c2ed3dc62b730.txt\",
            \"urlList\": $urls
          }"